site_name: (I002450) Practica Teledetectie 2020
nav:
    - Home: index.md
    - P3 - Beeldvoorbewerking: 
      - Introduction: P3-intro.md
      - Sentinel-2 intro and download: P3-Sentinel2.md
      - Introduction to SNAP: P3-Snap-intro.md
      - RGB colour composites: P3-colour-composites.md
      - Image preprocessing in SNAP: P3-image-preprocessing.md
      - RGB colour composites 2: P3-colour-composites-ctd.md
    - P4 - Intro tot Google Earth Engine:
      - Doel van het practicum: P4/P4-Goals.md
      - EarthEngine data catalog: P4/P4-DataCatalog.md
      - Introductie tot Earth Engine: P4/P4-Intro.md
      - Satellietdata oproepen, filteren en visualiseren: P4/P4-ImageVisualization.md
      - Reducing ImageCollections: P4/P4-Reducing.md
      - Cloud masking: P4/P4-Cloud_masking.md
      - (Extra) Oefeningen: P4/P4-Oefeningen.md
    - P5 - Feature Extraction:
      - Intro: P5/P5-Intro.md
      - Spectrale indices: P5/P5-Spectral_indices.md
      - Beeldstatistieken: P5/P5-ImageStatistics.md
      - Textuuranalyse: P5/P5-Texture.md
      - Principale componenten analyse: P5/P5-PCA.md
      - Oefeningen: P5/P5-Oefeningen.md
    - P6 - Beeldclassificatie:
      - Intro: P6/P6-intro.md
      - CASE - Mangrove monitoring in Suriname: P6/P6-SurinameCase.md
      - Niet-gesuperviseerde classificatie: P6/P6-Unsupervised.md
      - Gesuperviseerde classificatie: P6/P6-Supervised.md
      - Verbeteren van de classificatie: P6/P6-Improvement.md
      - Spectrale responsiecurves: P6/P6-SpectralResponse_oud.md
    - P7 - Tijdseries en SAR:
      - Tijdserie-analyse: P7/P7-Timeseries.md
      - SAR-analyse: P7/P7-SAR-tijdseries.md

theme:
  name: material
  palette:
    primary: teal
  language: nl
  features:
    - navigation.sections
    - navigation.tabs
  logo: "assets/images/LOGO_REMOSA_2020.jpg"
  favicon: "assets/images/LOGO_REMOSA_2020.jpg"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - mdx_math

plugins:
  - search

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML


use_directory_urls: false